apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-qouta
  namespace: limited

spec:
  hard:
    pods: "5"
    requests.cpu: "2"
    requests.memory: "1Gi"
    limits.cpu: "4"
    limits.cpu: "2Gi"
