apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dc
  labels:
    app: myapp
    type: front-end
spec:
  selector:
    matchLabels:
      app: myapp
      type: front-end
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
       - image: nginx
         imagePullPolicy: IfNotPresent
         name: nginx-container
  replicas: 3

