apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devuser-developer-rolebinding

subjects:
 - kind: User
   name: dev-user
   apiGroup: rbac.authorization.k8s.io

roleRef:
 kind: Role
 name: developer
 apiGroup: rbac.authorization.k8s.io



 #kubectl auth can-i create deployments --as dev-user        <---- use this to check 
