apiVersion: v1
kind: Pod
metadata:
  name: Config-map-test

spec:
  containers:
   - name: container1
     image: ubuntu
     imagePullPolicy: IfNotPresent
     args: ["echo","$APP_COLOR"]

     env:
      - name: db_passwd
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: db_passwd
     
     
     envFrom:
      - secretRef:
          name: app-secret


  # Pass the variables as files in a volume attached to container
  # can be found in /opt/app-secret-volume
     volumes:
      - name: app-config-volume
        secret:
          secretName: app-secret
