apiVersion: v1
kind: Pod
metadata:
  name: Config-map-test

spec:
  containers:
   - name: container1
     image: ubuntu
     imagePullPolicy: IfNotPresent
     args: ["echo","$APP_COLOR"]

     env:
      - name: APP_COLOR
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: APP_COLOR
     
     
     envFrom:
      - configMapRef:
          name: app-config


  # Pass the variables as files in a volume attached to container
     volumes:
      - name: app-config-volume
        configMap:
          name: app-config
