apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol-example1

spec:
  accessModes:
   - ReadWriteOnce
  
  persistentVolumeReclaimPolicy: Delete

  #  Retain ----> pv remains even if pvc is deleted, until manually deleted by admin
  #  Recycle ---->  pv's data is scrubbed and made available to other pvc to claim
  #  Delete ----> Delete the pv automatically as soon as pvc is deleted 
  
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data

    #to use AWS EBS instead of hostPath

 #awsElasticBlockStore:
  # volumeID: <volume-id>  
  # fsType: ext4 
