apiVersion: v1
kind: Secret
metadata:
  name: app-secret

  #to get the hashed value for secret use the command echo -n "TEXT-TO-CONVERT" | base64
  # to decode use command echo -n "HASHED VALUE" | base64 --decode
data:
  db_host: bXlzcWw=     # hashed value   echo -n "mysql" | base64
  db_user: cm9vdA==     # hashed value  echo -n "root" | base64
  db_password: cGFzc3dk  #hashed value   echo -n "passwd" | base64
